development:
  facebook_app_id: 1569512003376758
  facebook_app_secret: 594d4b99bad3ec6ba7de5acf56b5c3c9
  puma_env: development

staging:
  facebook_app_id: 1111210715608759
  facebook_app_secret: 24ad83bf183119c7e23f019b7e88b855
  puma_env: staging

production:
  facebook_app_id:
  facebook_app_secret:
  puma_env: production
