development:
  facebook_app_id: 541783899334178
  facebook_app_secret: 71edfc7346ac464e68c7ef43e00e4c08
  twitter_app_id: PAXJ24hYDjrUgZGIXAxijUPW9
  twitter_app_secret: 68UlOEIBcFQ0E3FX7PxSJ3nvT72ioXq7n8HbVPuFA08Doym42b
  puma_env: development 

staging:
  facebook_app_id: 820120514798274
  facebook_app_secret: 5775a2f2c953ad8e2e3646804314f461
  twitter_app_id: JB5x47kMvlX73gM0Aj2URdYJg
  twitter_app_secret: J7lJ71ZmWRo78WwEG0QvQQKkrL8PS3vR9uR0N2cVifa4NK5jbt
  puma_env: staging

production:
  facebook_app_id: 246953642340322
  facebook_app_secret: c48fe97d81d2469e58bf968a51e73fb5
  puma_env: production
