development:
  FACEBOOK_APP_ID: 541783899334178
  FACEBOOK_APP_SECRET: 71edfc7346ac464e68c7ef43e00e4c08
  API_USERNAME: aleksandar.popovic_api1.dvdpost.be
  API_PASSWORD: D8E7LMD43KXC7Y7S
  API_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31AJ2TkiC7osDf5Vnln60l.x17jJbL
  BILLING_AGREEMENT_DESCRIPTION: Plush Development Agreement
  APP_DOMAIN_URL: http://localhost:3000
  WEB_CONCURRENCY: 2
  MAX_THREADS: 5
  PORT: 3000
  RACK_ENV: development
  OGONE_PSPID: dvdpostogonetest
  OGONE_PASSWORD: KILLBILL1$metropolis
  OGONE_URL: https://ogone.test.v-psp.com/Tokenization/HostedPage
  OGONE_PARAMETERS_ACCEPTURL:  http://localhost:3000/ogone
  OGONE_PARAMETERS_EXCEPTIONURL: http://localhost:3000/en/steps/step3

staging:
  FACEBOOK_APP_ID: 820120514798274
  FACEBOOK_APP_SECRET: 5775a2f2c953ad8e2e3646804314f461
  API_USERNAME: pdg_api1.dvdpost.be
  API_PASSWORD: XNAWUUTK3QDXBZX5
  API_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31AvdfYT-vKIpEdGKkr7z3.i1H-EpR
  APP_DOMAIN_URL: http://staging.plush.be
  WEB_CONCURRENCY: 2
  MAX_THREADS: 5
  PORT: 3000
  RACK_ENV: staging
  OGONE_PSPID: dvdpostogonetest
  OGONE_PASSWORD: KILLBILL1$metropolis
  OGONE_URL: https://ogone.test.v-psp.com/Tokenization/HostedPage
  OGONE_PARAMETERS_ACCEPTURL:  http://staging.plush.be/api/v1/ogone_parameters_accepturl
  OGONE_PARAMETERS_EXCEPTIONURL: http://staging.plush.be/en/steps/step3

production:
  FACEBOOK_APP_ID: 246953642340322
  FACEBOOK_APP_SECRET: c48fe97d81d2469e58bf968a51e73fb5
  API_USERNAME: pdg_api1.dvdpost.be
  API_PASSWORD: XNAWUUTK3QDXBZX5
  API_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31AvdfYT-vKIpEdGKkr7z3.i1H-EpR
  APP_DOMAIN_URL: http://plush.be
  WEB_CONCURRENCY: 2
  MAX_THREADS: 5
  PORT: 3000
  RACK_ENV: production
  OGONE_PSPID: dvdpost
  OGONE_PASSWORD: KILLBILL
  OGONE_URL: https://secure.ogone.com/Tokenization/HostedPage
  OGONE_PARAMETERS_ACCEPTURL: http://www.plush.be/api/v1/ogone_parameters_accepturl
  OGONE_PARAMETERS_EXCEPTIONURL: http://www.plush.be/api/v1/ogone_parameters_exceptionurl
