development:
  facebook_app_id: 541783899334178
  facebook_app_secret: 71edfc7346ac464e68c7ef43e00e4c08
  puma_env: development

staging:
  facebook_app_id: 820120514798274
  facebook_app_secret: 5775a2f2c953ad8e2e3646804314f461
  puma_env: staging

production:
  facebook_app_id:
  facebook_app_secret:
  puma_env: production
