########################################################################################################################

development:
  adapter: mysql2
  encoding: utf8
  database: plush_development
  username: root
  password: #root
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock


common_development:
  adapter: mysql2
  encoding: utf8
  database: common_development
  username: root
  password: #root
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock

########################################################################################################################

#staging:
#  adapter: mysql2
#  encoding: utf8
#  database: plush_staging
#  username: webuser
#  password: 3gallfir-
#  host: 192.168.100.204
#  port: 3306

#common_staging:
#  adapter: mysql2
#  encoding: utf8
#  database: common_staging
#  username: webuser
#  password: 3gallfir-
#  host: matadi
#  port: 3306

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plush_production
  pool: 5
  username: webuser
  password: 3gallfir-
  host: 192.168.100.204

common_staging:
  adapter: mysql2
  encoding: utf8
  database: common_production
  username: webuser
  password: 3gallfir-
  host: matadi
  port: 3306

########################################################################################################################

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plush_test
  pool: 5
  username: root
  password: matrix
  host: 127.0.0.1

common_test:
  adapter: mysql2
  encoding: utf8
  database: common_test
  username: root
  password: matrix
  host: 127.0.0.1

########################################################################################################################

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plush_production
  pool: 5
  username: webuser
  password: 3gallfir-
  host: 192.168.100.204

common_production:
  adapter: mysql2
  encoding: utf8
  database: common_production
  username: webuser
  password: 3gallfir-
  host: matadi
  port: 3306

########################################################################################################################
