################################################################################################################################################################
# development: common_development:
################################################################################################################################################################

development:
  adapter: mysql2
  encoding: utf8
  database: plush_production
  username: root
  password: #root
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock


common_development:
  adapter: mysql2
  encoding: utf8
  database: common_production
  username: root
  password: #root
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock

################################################################################################################################################################
# staging: common_staging:
################################################################################################################################################################

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plush_production
  pool: 5
  username: webuser
  password: 3gallfir-
  host: 192.168.100.204

common_staging:
  adapter: mysql2
  encoding: utf8
  database: common_production
  username: webuser
  password: 3gallfir-
  host: matadi
  port: 3306

################################################################################################################################################################

################################################################################################################################################################

test:
  adapter: mysql2
  encoding: utf8
  database: plush_production
  username: root
  password: #root
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock

common_test:
  adapter: mysql2
  encoding: utf8
  database: common_production
  username: root
  password: #root
  host: localhost
  port: 3306
  socket: /opt/lampp/var/mysql/mysql.sock

################################################################################################################################################################

################################################################################################################################################################

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plush_production
  pool: 5
  username: webuser
  password: 3gallfir-
  host: 192.168.100.204

common_production:
  adapter: mysql2
  encoding: utf8
  database: common_production
  username: webuser
  password: 3gallfir-
  host: matadi
  port: 3306

################################################################################################################################################################
