development:
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
test:
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
staging:
  mysql41: 9312
  pid_file: /home/webapps/plush/staging/shared/tmp/searchd.pid
  indices_location: /home/webapps/plush/staging/shared/db/sphinx
  max_matches: 10000
  mem_limit: 128M
pre_production:
  mysql41: 9313
  pid_file: /home/webapps/plush/pre_production/shared/tmp/searchd.pid
  indices_location: /home/webapps/plush/pre_production/shared/db/sphinx
  max_matches: 10000
  mem_limit: 128M
production:
  mysql41: 9314
  pid_file: /home/webapps/plush/pre_production/shared/tmp/searchd.pid
  indices_location: /home/webapps/plush/pre_production/shared/db/sphinx
  max_matches: 10000
  mem_limit: 128M
