development:
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 1000
  mem_limit: 128M
test:
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 1000
  mem_limit: 128M
staging:
  mysql41: 9316
  pid_file: /home/webapps/plush/staging/shared/tmp/searchd.pid
  indices_location: /home/webapps/plush/staging/shared/db/sphinx
  max_matches: 1000
  mem_limit: 128M
pre_production:
  mysql41: 9317
  pid_file: /home/webapps/plush/pre_production/shared/tmp/searchd.pid
  indices_location: /home/webapps/plush/pre_production/shared/db/sphinx
  max_matches: 1000
  mem_limit: 128M
production:
  mysql41: 9318
  pid_file: /home/webapps/plush/pre_production/shared/tmp/searchd.pid
  indices_location: /home/webapps/plush/pre_production/shared/db/sphinx
  max_matches: 1000
  mem_limit: 128M
